name: release

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Zip the Build
        run: zip -r ${{ steps.get_version.outputs.VERSION }}} ./docs/
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: Release latest
          files: |
            ${{ steps.get_version.outputs.VERSION }}}.zip