name: release

on: push
permissions:
  contents: write
  discussions: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Zip the Build
        run: zip -r mkdocs_latest ./docs/
      - name: Check dir
        run: ls -l
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: Release latest
          files: |
            mkdocs_latest.zip